FI-3222: DTR Client Tests: Use Random Number for Attestation Continuation Links
inferno-framework/davinci-dtr-test-kit pull request #20
Opened 2024-10-11 02:21 UTC by degradification

# Description

This ticket updated the Full EHR and SMART App attestation tests to use random ids instead of client id tokens

## Important Changes

Removed client id tokens and replaced with random id tokens for the following files
- `lib/davinci_dtr_test_kit/client_groups/dinner_static/dtr_full_ehr_launch_attestation_test.rb`
- `lib/davinci_dtr_test_kit/client_groups/dinner_static/dtr_full_ehr_prepopulation_attestation_test.rb`
- `lib/davinci_dtr_test_kit/client_groups/dinner_static/dtr_full_ehr_prepopulation_override_attestation_test.rb`
- `lib/davinci_dtr_test_kit/client_groups/dinner_static/dtr_full_ehr_rendering_enabled_questions_attestation_test.rb`
- `lib/davinci_dtr_test_kit/client_groups/dinner_static/dtr_full_ehr_store_attestation_test.rb`
- `lib/davinci_dtr_test_kit/client_groups/dinner_static/dtr_smart_app_prepopulation_attestation_test.rb`
- `lib/davinci_dtr_test_kit/client_groups/dinner_static/dtr_smart_app_prepopulation_override_attestation_test.rb`
- `lib/davinci_dtr_test_kit/client_groups/dinner_static/dtr_smart_app_rendering_enabled_questions_attestation_test.rb`

`lib/davinci_dtr_test_kit/client_groups/resp_assist_device/dtr_questionnaire_rendering_attestation_test.rb`
- Fixed Typos
- Did not update the client id as it was not specified in the ticket

## Testing Recommendations

Make sure all unit tests pass (unit tests were not added for this pull request), and the application runs as expected. Also ensure the attestation tests in the test suite do not ask for a client id token.

# Checklists

**Submitter:**
- [x] This MR describes why these changes were made.
- [x] This MR is into the correct branch (usually 'main').
- [x] Comment added to the relevant Jira ticket(s) with a link to this MR.
- [x] The relevant Jira ticket has been moved to 'Peer Review' (may be N/A if a Jira ticket is associated with multiple MRs)
- [x] Code diff has been reviewed (it **does not** contain: additional white space, not applicable code changes, debug statements, etc.).
- [x] Ensure automated tests pass successfully.

**Final Merger**
- [ ] The necessary number of reviews/approvals have been received on this PR and all checklists have been completed.
- [ ] The relevant Jira ticket has been moved to 'Done' (may N/A if a Jira ticket is associated with multiple MRs)

2024-10-11 17:58 UTC, karlnaden commented
The changes Look good. While we're doing this, I would change the use of client_id in dtr_questionnaire_rendering_attestation_test.rb because it also means that the client_id input gets added to a group that it wouldn't otherwise be on (all others are involved in communication with inferno, so its already needed). This will ideally require a few other changes
- change the parameter name from client_id to token or something similar that doesn't suggest this is a non-random value
- change the definition of the resume routes in lib/davinci_dtr_test_kit/dtr_smart_app_suite.rb to extract the session identifier from the new parameter name using the extract_token_from_query_params

2024-10-11 18:02 UTC, karlnaden requested changes
see my comment on one place to replace the use of client_id

2024-11-20 03:05 UTC, karlnaden reviewed
one last question.

2024-11-20 18:14 UTC, vanessuniq commented on lib/davinci_dtr_test_kit/client_groups/resp_assist_device/dtr_questionnaire_rendering_attestation_test.rb
> +    config(options: { token: SecureRandom.uuid })
Actually, I found a simpler way, keeping the token in the run block. will reach out to Dalton to refactor and keep it simple before we merge it.

2024-11-21 14:23 UTC, karlnaden approved these changes

2024-11-21 15:11 UTC, merged