FI-3463: DTR Light EHR: test supported payer endpoint
inferno-framework/davinci-dtr-test-kit pull request #42
Opened 2024-12-16 18:28 UTC by degradification

# Description

This ticket adds a test for DTR Light EHR requirement 102 to the DTR Light EHR suite. This defines an endpoint, which Inferno can respond to requests and return conformant information.

## Important Changes

`lib/davinci_dtr_test_kit/client_groups/light_ehr/dtr_light_ehr_supported_endpoints_group.rb`
- Defined the supported endpoints group

`lib/davinci_dtr_test_kit/client_groups/light_ehr/dtr_light_ehr_supported_payer_endpoint_test.rb`
- Defined the test that the app can access the supported payer endpoint via a GET request & checks the header

`lib/davinci_dtr_test_kit/client_groups/light_ehr/dtr_light_ehr_supported_payers_accept_header_test.rb`
- Defined the test that the app can accept the header (application/json)

`lib/davinci_dtr_test_kit/client_groups/light_ehr/dtr_light_ehr_supported_payers_user_response_test.rb`
- Defined the test that a user can provide a user_response JSON and checks for validations

`lib/davinci_dtr_test_kit/dtr_light_ehr_suite.rb`
- Defined the route for the new endpoint

`lib/davinci_dtr_test_kit/dtr_light_ehr_suite.rb`
- Added requires
- Defined the suite_endpoint
- Added the group for the supported endpoints

`lib/davinci_dtr_test_kit/endpoints/mock_payer/light_ehr_supported_payer_endpoint.rb`
- A GET route /supported-payers was defined to return a JSON response with a list of payers, each payer contains id & name

`spec/davinci_dtr_test_kit/dtr_light_ehr_supported_payer_endpoint_test_spec.rb`
- Implement unit tests for DTRLightEHRSupportedPayerEndpoint
- Test simulates a request to the endpoint and checks that the test waits for the request and then passes if received

`spec/davinci_dtr_test_kit/dtr_light_ehr_supported_payers_accept_header_test_spec.rb`
- Implement unit tests for DTRLightEHRAcceptHeaderTest
- Test checks if the header is application/json

`spec/davinci_dtr_test_kit/dtr_light_ehr_supported_payers_user_response_test_spec.rb`
- Implemented unit tests for DTRLightEHRUserResponseTest
- Test checks if the user_response is valid, invalid, and a no input

`lib/davinci_dtr_test_kit/tags.rb`
- Added tag for light ehr endpoint

`lib/davinci_dtr_test_kit/urls.rb`
- Added supported payer path & url

## Testing Recommendations

Make sure all unit tests pass including the ones that were added to this pull request, and the application runs as expected. Run the Light EHR tests to test both expected successes and expected failures with the postman collection `config/DTR LIGHT EHR Tests API.postman_collection.json`. 

# Checklists

**Submitter:**
- [x] This MR describes why these changes were made.
- [x] This MR is into the correct branch (usually 'main').
- [x] Comment added to the relevant Jira ticket(s) with a link to this MR.
- [x] The relevant Jira ticket has been moved to 'Peer Review' (may be N/A if a Jira ticket is associated with multiple MRs)
- [x] Code diff has been reviewed (it **does not** contain: additional white space, not applicable code changes, debug statements, etc.).
- [x] Ensure automated tests pass successfully.

**Final Merger**
- [x] The necessary number of reviews/approvals have been received on this PR and all checklists have been completed.
- [x] The relevant Jira ticket has been moved to 'Done' (may N/A if a Jira ticket is associated with multiple MRs)

2024-12-19 22:23 UTC, vanessuniq requested changes
Move the `url` input from the suite level to the specific groups that require it, so that it is not required for the supported enpoint group.

2024-12-19 22:23 UTC, vanessuniq commented on lib/davinci_dtr_test_kit/endpoints/mock_payer/light_ehr_supported_payer_endpoint.rb
> +      end
Modify this logic so that it fails if the `Accept` header is not `application/json` and passes otherwise.

2024-12-19 22:23 UTC, vanessuniq commented on spec/davinci_dtr_test_kit/dtr_light_ehr_supported_endpoints_group_spec.rb
> +RSpec.describe DaVinciDTRTestKit::DTRLightEhrSupportedEndpointsGroup do
write spec for the Test directly instead of the group.

2025-02-19 20:50 UTC, karlnaden commented on lib/davinci_dtr_test_kit/client_groups/light_ehr/dtr_light_ehr_user_response_test.rb
> +      end
This isn't loading the user response when it is used. You might just always validate the request.response_body.

2025-02-19 20:54 UTC, karlnaden commented on spec/davinci_dtr_test_kit/dtr_light_ehr_user_response_test_spec.rb
> +    url += "?user_response=#{ERB::Util.url_encode(user_response)}" if user_response.present?
This is the wrong place for this to go - should be in the response body. I think this was something you did previously, but need to update.

2025-02-20 20:16 UTC, karlnaden commented on spec/davinci_dtr_test_kit/dtr_light_ehr_user_response_test_spec.rb
> +      response_body: {}.to_json
user response should be in the response body.

2025-02-27 20:54 UTC, vanessuniq commented on lib/davinci_dtr_test_kit/client_groups/light_ehr/dtr_light_ehr_user_response_test.rb
> +        return
no need to return

2025-02-27 20:54 UTC, vanessuniq commented on lib/davinci_dtr_test_kit/client_groups/light_ehr/dtr_light_ehr_user_response_test.rb
> +    input :unique_url_id, type: :text
do we need this input for this test?

2025-02-27 20:54 UTC, vanessuniq commented on lib/davinci_dtr_test_kit/client_groups/light_ehr/dtr_light_ehr_user_response_test.rb
> +      payer.is_a?(Hash) && payer.key?('id') && payer.key?('name')
same here, provide a specific and detailed error message explaining why the response is invalid

2025-02-27 20:54 UTC, vanessuniq commented on lib/davinci_dtr_test_kit/client_groups/light_ehr/dtr_light_ehr_user_response_test.rb
> +      parsed_response['payers'].all? { |payer| valid_payer?(payer) }
We should provide a specific and detailed error message explaining why the response is invalid: response is not a hash, payers field not present, etc.

2025-02-28 15:46 UTC, karlnaden commented on lib/davinci_dtr_test_kit/client_groups/light_ehr/dtr_light_ehr_user_response_test.rb
> +      request_record = requests.find { |r| r.tags.include?(SUPPORTED_PAYER_TAG) }
shouldn't need this line - the tagged requests should be put into the `request` variable, so you can just use that.

2025-02-28 15:47 UTC, karlnaden commented on lib/davinci_dtr_test_kit/client_groups/light_ehr/dtr_light_ehr_user_response_test.rb
> +      parsed_response['payers'].all? { |payer| valid_payer?(payer) }
agreed

2025-02-28 15:50 UTC, karlnaden commented on lib/davinci_dtr_test_kit/client_groups/light_ehr/dtr_light_ehr_accept_header_test.rb
Let's make clear somehow that this is related to the supported payers endpoint in the file name, class name, and id. Recommendations:
- file: dtr_light_ehr_supported_payers_accept_header_test
- class: DTRLightEHRSupportedPayersAcceptHeaderTest
- id: : dtr_light_ehr_sp_accept_header (NOTE: shortened supported payers in the id only because long ids get problematic)

2025-02-28 15:54 UTC, karlnaden commented on lib/davinci_dtr_test_kit/client_groups/light_ehr/dtr_light_ehr_user_response_test.rb
> +    title 'Checks for a valid user response at the supported payer endpoint'
We have a convention to put `[USER INPUT VERIFICATION]` at the beginning of the title of these tests that check user input for simulation purposes. Please add

2025-02-28 15:59 UTC, karlnaden commented on lib/davinci_dtr_test_kit/client_groups/light_ehr/dtr_light_ehr_user_response_test.rb
> +      when a request is made to the supported payer endpoint.
```suggestion
      This test verifies that the user-provided response conforms
      to the requirements for a supported payers response. The test will
      be omitted if the tester does not provide a custom response in the
      **Custom Supported Payers Response** input.
```

2025-02-28 16:01 UTC, karlnaden commented on lib/davinci_dtr_test_kit/client_groups/light_ehr/dtr_light_ehr_supported_payer_endpoint_test.rb
> +          description: %(
```suggestion
    input :unique_url_id,
          title: 'Supported Payers Endpoint Path',
          description: %(
```

2025-02-28 16:03 UTC, karlnaden commented on lib/davinci_dtr_test_kit/client_groups/light_ehr/dtr_light_ehr_supported_payer_endpoint_test.rb
> +          ```
You can remove these lines since the identification is part of the URL already provided above. This kind of language is used when we have additional headers.

2025-03-03 14:28 UTC, karlnaden commented on lib/davinci_dtr_test_kit/client_groups/light_ehr/dtr_light_ehr_supported_endpoints_group.rb
> +      the supported endpoint capabilities as defined by the DaVinci Documentation
```suggestion
      the supported payers endpoint capabilities as defined by the DaVinci Documentation
```

2025-03-03 14:31 UTC, karlnaden commented on lib/davinci_dtr_test_kit/client_groups/light_ehr/dtr_light_ehr_supported_payers_accept_header_test.rb
> +    )
```suggestion
    title 'Client uses the required Accept HTTP header value'
    description %(
      This test verifies that the request to the supported payers endpoint
      includes an `Accept` HTTP header set to `application/json`.
    )
```

2025-03-03 14:39 UTC, karlnaden commented on lib/davinci_dtr_test_kit/client_groups/light_ehr/dtr_light_ehr_supported_payers_endpoint_test.rb
> +          ),
```suggestion
          description: %(
            If present, the value will be returned when the client makes a request to the supported payers endpoint,
            allowing testers to instruct Inferno how to respond with payers that are configured in the
            system under test. The provided response will be checked for conformance to the required
            JSON structure. If not provided, Inferno will return a pre-configured value.
          ),
```

2025-03-03 14:41 UTC, karlnaden commented on lib/davinci_dtr_test_kit/client_groups/light_ehr/dtr_light_ehr_supported_endpoints_group.rb
> +      )
```suggestion
    description %(This test group tests system for their ability to request and react to a DTR
      SMART App's [list of supported payers](https://hl7.org/fhir/us/davinci-dtr/STU2/specification.html#determination-of-payers-supported-by-a-dtr-app).
    )
```

2025-03-03 14:42 UTC, karlnaden commented on lib/davinci_dtr_test_kit/client_groups/light_ehr/dtr_light_ehr_supported_endpoints_group.rb
> +      )
```suggestion
    description %(This group checks that systems can request and react to a DTR
      SMART App's [list of supported payers](https://hl7.org/fhir/us/davinci-dtr/STU2/specification.html#determination-of-payers-supported-by-a-dtr-app).
    )
```

2025-03-03 14:44 UTC, karlnaden commented on lib/davinci_dtr_test_kit/client_groups/light_ehr/dtr_light_ehr_supported_payers_user_response_test.rb
> +    )
```suggestion
    title %(
      [USER INPUT VERIFICATION] Tester-provided supported payers response is conformant
    )
    description %(
      This test verifies that the user-provided response conforms
      to the requirements for a supported payers response. The test will
      be omitted if the tester does not provide a custom response in the
      **Custom Supported Payers Response** input.
    )
```

2025-03-03 14:47 UTC, karlnaden commented on lib/davinci_dtr_test_kit/client_groups/light_ehr/dtr_light_ehr_supported_payers_user_response_test.rb
> +      pass_if user_response.nil?, 'No user response provided, skipping validation and using default response.'
```suggestion
      omit_if user_response.nil?, 'No user response provided, default response returned.'
```

2025-03-03 14:50 UTC, karlnaden commented on lib/davinci_dtr_test_kit/client_groups/light_ehr/dtr_light_ehr_supported_payers_user_response_test.rb
> +    input :user_response, type: :textarea, optional: true
```suggestion
    input :user_response, type: :textarea, optional: true
```

2025-03-03 14:55 UTC, karlnaden commented on lib/davinci_dtr_test_kit/client_groups/light_ehr/dtr_light_ehr_supported_payers_endpoint_test.rb
> +          Inferno will return the static payers json details
```suggestion
          ### Supported Payer Endpoint

          Inferno will wait for the Light EHR to to make a GET request to

          `#{supported_payer_url(unique_url_id)}`
```

2025-03-03 20:59 UTC, karlnaden approved these changes

2025-03-03 21:15 UTC, merged